### ISSUE TITLE
missing TextType implementation

### ISSUE THREAD

**Issue by mbjones** [ropensci/EML#124]
Several fields that in EML are typed as `TextType`, such as `abstract` and `intellectualRights`, are produced via the R EML package as if they were simply character strings.  I may be missing it, but I don't see a mechanism for adding the `para` and `section` elements of the `TextType`.

**Comment by cboettig** [comment]
Done by `eml2` merge, 0358852ec27d262a2e9d92a4b7f6835ffd7d8e59.
`para` and `section` are now child slots for any `TextType`, though a bit special in that they allow direct XML, since construction of docbook markup as S4 slots doesn't really make sense.  (note that the internationalization methods with `value` elements also fully implemented).
