### ISSUE TITLE
no check for definition length to match column #

### ISSUE THREAD

**Issue by rBatt** [ropensci/EML#131]
in `eml_dataTable` it would be helpful if there was an initial check to unsure that the length of the arguments `col.defs` and `unit.defs` matched `ncol(dat)`.

I was getting pretty confusing behavior when I had accidentally only defined 36 of the 37 columns – I was being prompted to define the `unitType` of one of the values in an element of my `unit.def`. Took me a while to track down the error because I thought it was due to a mismatch between column class and the definitions, but really it was trying to apply the definitions to the wrong column.

**Comment by mbjones** [comment]
Good idea. I agree.

**Comment by cboettig** [comment]
+1.  

I wonder if we should rethink the data structure for specifying these things in order to make it harder to make that kind of error in the first place?  For instance, it might be better to specify the column definition and the unit definitions in the same data structure to make sure they are aligned properly.  

Originally we had something closer to this: instead of `unit.defs` and `col.defs` you just gave one list called `meta` which had to be structured with one list element per column, in which each element was itself a list which had the column name, column definition, and unit definition.  However, this kind of deeply nested list structure seems kind of fragile and complex (e.g. the kind of thing you might define a custom S3 class for, but that starts to feel like we're just re-inventing the attributeList S4 object we already have; which matches the EML definition more precisely.  

I wonder if it would be better to ask the user to define this data in a data.frame rather than in nested lists.  A data.frame would also impose the constraint of not miss-matching metadata, (ironically each row of this metadata `data.frame` would define a column of the actual data).  Though perhaps the idea of having a vector of factor definitions in a single cell of a data.frame is too off-putting to consider...

Having a really natural way to do this part, (including custom unit definitions) has long been a stumbling block for me; I've been hesitant to move towards a CRAN release until I feel like we won't need to change the function API.  The current `unit.defs` & `col.defs` still feels a bit too clumsy.

**Comment by rBatt** [comment]
I agree that it's tough to think of how things should be organized.

My biggest challenge has been figuring out what should be filled in, and
*how* it can be filled in (e.g., it was a surprise to me that I could only
list 1 contact). Keep in mind that I'm learning about EML via this package,
so for me it's really an intro to metadata as well. Regardless, the only
thing that feels clumsy about the definitions, to me, is that what I supply
to unit.defs is so varied, and I'm not really sure what I can or should
supply.

You could also require that the unit and col defs be named, and make sure
the names match.

**Comment by cboettig** [comment]
Merge in of `eml2` deprecates the `unit.defs` & `col.defs` method in favor of using a data.frame to specify attribute metadata, as discussed in https://github.com/cboettig/eml2/issues/11, (will document properly in README & vignettes soon).  Each attribute (column in the data being documented) is a row in this attribute `data.frame`; the `data.frame` structure naturally enforces alignment of unit defs and col.defs, avoiding the above-mentioned miss-match possibility.
