### ISSUE TITLE
eml_coverage() fails to handle xsd:gYear values

### ISSUE THREAD

**Issue by mbjones** [ropensci/EML#133]
The `eml_coverage()` method works fine with ISO date values in its `dates` argument, but if the date value is changed to a `gYear` value (which is valid in the EML specification as an `xsd:gYear`), then instead a NA is entered in the date fields.  To illustrate, note the NA values in the second invocation below:

```r
library(EML)
> eml_coverage(dates=c('2010-01-01', '2015-01-01'))
temporalCoverage:
  rangeOfDates:
    beginDate:
      calendarDate: '2010-01-01'
    endDate:
      calendarDate: '2015-01-01'
> eml_coverage(dates=c('2010', '2015'))
temporalCoverage:
  rangeOfDates:
    beginDate:
      calendarDate: NA
    endDate:
      calendarDate: NA
```

**Comment by cboettig** [comment]
@mbjones Thanks, should be fixed in master version.

The original version of `eml_coverage` was too opinionated, it wanted to make your date look like an ISO8601 format even if you gave it in another format (more particularly, it wanted to convert your string to a dateTime object).  

To avoid these issues I've just dropped that part so now you can give it any string, which means that `eml_coverage()` can create invalid EML if you give it some random character string instead.  

It's not clear to me what the desired behavior for `eml_coverage()` should be with regards to date.  Should it be throwing an error if the date does not meet the schema format?  If so, how should that be implemented?

This highlights a kind of deeper design question I'd like your take on.  Currently we represent EML internally as S4 object classes, but we don't include validation in the class definitions, leaving validation up to the EML validator.  Adding object validation is perhaps the most general way to get the desired error behavior, but feels like we do a lot of manual re-coding of something that's already specified in the schema and we're just increasing the chance for errors.  (We already do a lot of this in just defining the classes, which makes the package a lot of lines of code relative to it's function, but then generating this stuff programmatically from the schema has never worked out for us.)

**Comment by mbjones** [comment]
@cboettig Thanks for fixing that, Carl.  Given that you are not doing validation in the S4 classes (yet), it seems reasonable to just let the user pass in what they want, and do our best to convert it.  It would be nice if it could take a dateTime object as well and extract the right string if that is what it is given.  But if its given a string or number, it should probably just pass it through as you do now and assume the user knows what content is needed.

Regarding validation, its a challenge.  The EML Parser does effective validation, but it passes back really cryptic error messages, which users universally complain about.  If you inspect them carefully, they contain everything you need to know about where validation failed, but this has proven too much for most people.  In our metadata apps like Morpho, we tend to try to catch validation errors at input time, so the user is still on that 'section' of metadata, and we can highlight where the problem occurred.  The equivalent in R would be to point out the validation error when an element is created.   But not all validation errors can be caught at the sub-element level -- sometimes you have to know the whole content model to determine whether an element is valid or not.  So, even if you do validate in the S4 classes, you'll need to validate at the top level as well to ensure all of the elements fit together properly.  Plus, I agree that re-coding the validation rules in the S4 classes would be both tedious and error prone.

As an aside, we're going to start using the EML package a lot for creating thousands of metadata files, so we'll probably find a bunch of issues.  We can help fix them too.

**Comment by cboettig** [comment]
Thanks for the feedback, very helpful.
