### ISSUE TITLE
adding `directory` XML attribute to EML document

### ISSUE THREAD

**Issue by mbjones** [ropensci/EML#135]
@cboettig We want to use the EML `userId` element within the creator field, but it requires the `directory attribute to be set.  I'm unclear how to do that.  In the end, the EML we want would be:

```xml
<creator>
    <individualName>
        <givenName>Matthew</givenName>
        <surName>Jones</surName>
    </individualName>
    <userId directory="http://orcid.org">http://orcid.org/0000-0003-0077-4738</userId>
</creator>
```

In the R client, I think you would do:
```R
eml@dataset@creator[[1]]@userID <- "http://orcid.org/0000-0003-0077-4738"
```
I'm not sure right off how you set the required `directory` attribute in the EML package. Any pointers? 

Also, in party_classes.R, shouldn't the responsibleParty `userID` slot be `userId` to match the EML capitalization? 

Thanks.

**Comment by cboettig** [comment]
Okay, think this is fixed on the `eml-basics` branch (which strips out some of the deprecated dependencies like the publish to figshare or old dataone package).  

@mbjones also see my email about eml2, hope we can avoid all these incomplete-implementations in the current version (e.g. almost all are like this where some node is just a "character" instead of a full implementation of the element/complexType).

**Comment by mbjones** [comment]
Thanks @cboettig we'll give it a spin.

**Comment by mbjones** [comment]
@cboettig I tried it, but ran into an error when trying to load the package:  

```
Loading EML
Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  (from party_classes.R#68) : 
  no definition was found for superclass “eml-2.1.1” in the specification of class “userID”
```

Just pushed a fix in sha 3ee931b. Can you see if that still works for you?

**Comment by cboettig** [comment]
Whoops, guess i didn't push second commit; Travis also caught that one.
Fix looks good by eyeball

On Tue, Feb 2, 2016, 3:51 PM Matt Jones <notifications@github.com> wrote:

> @cboettig <https://github.com/cboettig> I tried it, but ran into an error
> when trying to load the package:
>
> Loading EML
> Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  (from party_classes.R#68) :
>   no definition was found for superclass “eml-2.1.1” in the specification of class “userID”
>
> Just pushed a fix in sha 3ee931b
> <https://github.com/ropensci/EML/commit/3ee931b2cacfe40a149b69d1eb8a1115ffcc3ae4>.
> Can you see if that still works for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/EML/issues/135#issuecomment-178893102>.
>
-- 

http://carlboettiger.info

**Comment by mbjones** [comment]
Also ran into a problem whereby the fix did not serialize the `directory` as an attribute, plus it got the case wrong of the `userId` element. Fixed both in sha 670825bc29525a4d0ddb480829ffc80f3341ac45, even though I know you are working on eml2. This is only on the branch at this point -- not sure how you plan to merge to master.

**Comment by cboettig** [comment]
Hi @mbjones ,

Thanks.  Can you see if you can use `eml2` instead of EML now?  Or otherwise let me know if there is any functionality that EML has that we don't have in `eml2` that I can prioritize?  

It is pretty stripped down in terms of helper functions, but the class definitions are much more complete and accurate, and it should avoid (almost all of?) these issues.  

Good question, not sure how best to deal with EML branches.  Ultimately I think it would just make sense to deprecate the whole package; though maybe I should just merge `eml-basics` back onto master first all the same.  Thoughts?

**Comment by ivanhanigan** [comment]
Dear @cboettig, 
I am keenly following your EML developments as you know, ever since the first `reml` package.
I'd just like to ask what is the rationale for creating the new `eml2` and deprecating `EML`?
It seems that you have made major modifications to the way you set up `EML`, and now aim to deprecate it, and move forward with the replacement `eml2` instead.  My question is why not just make this a major version bump to the `EML` package?  There may be some pain for users to migrate, but it would provide continuity to myself (and my old team who run a `metacat` portal). We have documentation and R scripts pointing to the `EML` package as the tool we use to provide additional functionality that we could not get out of `morpho` and I'd prefer to upgrade to `EMLv2.0` rather than remove `EML` and install `eml2`.
Re: dealing with branches.  I also see pros and cons of different approaches but have recently decided to take on board much of the recommendations of this article http://nvie.com/posts/a-successful-git-branching-model/ (image is below... )

Is that what you mean about 'best way to deal with EML branches? sorry if I misunderstand).

PS I guess my other thought is that perhaps `eml2` provides standalone functions that `EML` could use - perhaps it might be `eml-helpers` or such?

Thanks again for your works! 
![nvie-git](https://cloud.githubusercontent.com/assets/1305767/13124751/fecd1122-d615-11e5-96eb-39e588c0c1c3.png)

**Comment by cboettig** [comment]
@ivanhanigan Thanks, you are right on point.  `eml2` is a complete rewrite, since most of the code is generated programmatically from the EML schema rather than written by hand as it was here (which is both less complete and more error-prone).  Hence I started it as a new repo rather than a branch of this repo.  `eml2` also aims to address all the limitations that led to me never actually releasing this EML to CRAN.  

Once `eml2` is minimally functional / stable (almost now), we could just merge it in here as `EML 2.0` a la semantic versioning to indicate breaking changes. I suppose the plus side of that is that any links to this repo will now discover the new version.  Is that what you mean by continuity?  Since EML was never on CRAN, it's not like a user can run `updatePackages` and get the newer version anyhow; so doing an install of `EML` vs an install of `eml2` seems about the same amount of effort (note that there is no need to remove `EML` in order to install `eml2`).  

On the downside moving `eml2` here will almost certainly break any code that was using this EML.  My assumption has been that the EML package didn't get much traction (always being a bit clunky and never being on CRAN) so I've assumed any users intrepid enough to be using it would be able to migrate to `eml2` in either way.

**Comment by mbjones** [comment]
@cboettig We could try to start using the eml2 package, but it will take a bit as we have some short-term deliverables that are currently built using the EML functions.  Like @ivanhanigan, I'd rather see it as a new release of EML for continuity, even if its released to cran as version 2.x (which, nicely would correspond to the EML metadata release as well). And it would have the advantage of not having to explain what the '2' is in the name -- this would be the first truly production release of the package.  So far, I've reviewed the eml2 code and looked at some of the examples, but haven't tried putting it through any real paces.  I'll try to do so sometime soon.

**Comment by cboettig** [comment]
@mbjones Great, thanks.  Will plan to merge into EML repo then as soon as `eml2` has minimal functionality.  Just have to figure out what that entails.  

Can you give me any hints as to what EML functions you are using currently?  I can try porting over the functions & methods in the EML namespace, but I think some are poorly designed and would be better to deprecate.  Getting a better sense of how you and @ivanhanigan are using EML could also inform what functions need to be in `eml2` before we port it over here.

**Comment by mbjones** [comment]
@cboettig In the current script we are writing, we are using the functions and slots shown below.  We are reading in a template EML document, then using R to add in a bunch of details from hundreds of thousands of tar and netcdf files.  You'll notice that a lot of the time we're directly manipulating slots in constructed objects.  We're not at all wedded to this API, and are mostly using what is there, so let's go ahead and change it to whatever makes sense and is easiest to use.  We'll adapt.

```R
eml <- eml_read('somefile')
eml@packageId <- newPkgId
eml@dataset@title <- paste('Past and future simulations of', 
    varTab[which(varTab$varCode==variable),'variable'],
    'from the Levy et al. microclimate model, United States of America')
eml@dataset@creator[[1]]@userId <- new("userId")
eml@dataset@creator[[1]]@userId@userId <- "http://orcid.org/0000-0003-0920-1207"
eml@dataset@creator[[1]]@userId@directory <- "http://orcid.org"
oe <- new('otherEntity',entityName=df[i,'filename'])
oe@entityDescription <- paste("Compressed file containing netcdf data files of hourly estimates of",
    df[i,'scenario'], varTab[varTab$varCode==vaR,'variable'], 
    "in region", df[i,'region'],"in the USA (see attached map and files table)", sep=" ")
#oe@physical@objectName=paste('obj',df[i,'filename'],sep='')
#oe@physical@dataFormat<-'application/octet-stream'
oe@entityType <- 'netCDF'
oe@coverage <- eml_coverage(
    dates <- c(as.character(datesTab[datesTab$scenario=='past','begin']),
                     as.character(datesTab[datesTab$scenario=='past','end'])),
    geographic_description <- paste('Subregion of the United States of America,',df[i,'region'], 
                     '(see attached map and bounding coordinates)',sep=' '),
    NSEWbox =  c(grid1[grid1$label==df[i,'region'],'nw_lat'],
                            grid1[grid1$label==df[i,'region'],'se_lat'],
                            grid1[grid1$label==df[i,'region'],'se_lon'],
                            grid1[grid1$label==df[i,'region'],'nw_lon']),
    scientific_names = NULL)
    # attribute list
    oe@attributeList <- eml_attributeList(col.names = c(ncFile$var[[1]]$name,
                                                        ncFile$var[[2]]$name,
                                                        ncFile$var[[3]]$name,
                                                        ncFile$var[[4]]$name,
                                                        ncFile$var[[5]]$name),
                                          col.defs =  c(ncFile$var[[1]]$longname,
                                                        ncFile$var[[2]]$longname,
                                                        ncFile$var[[3]]$longname,
                                                        ncFile$var[[4]]$longname,
                                                        ncFile$var[[5]]$longname),
                                          unit.defs = c(ncFile$var[[1]]$units,
                                                        ncFile$var[[2]]$units,
                                                        ncFile$var[[3]]$units,
                                                        ifelse(ncFile$var[[4]]$units=='','dimensionless',
                                                            ncFile$var[[4]]$units), 
                                                        ncFile$var[[5]]$units))
eml@dataset@otherEntity[i] <- oe
write.eml(eml,  file='levyMetadata',title='pkgMetadata',creator='jcouture')
```

**Comment by cboettig** [comment]
`directory` attribute and `userId` element name are fixed by merge of `eml2` repo into EML master (as @ivanhanigan suggested above); closing this issue.

To address other things in this thread: Overall creation of EML should be easier now using `new()` constructors (which now use custom `initialize` methods to streamline coercion to appropriate types and `ListOf` objects), with a few functions to facilitate creating certain more complex patterns (e.g. `set_attributes()`), though these are still in development.
