### ISSUE TITLE
Error in metaclasses[[s]] : attempt to select less than one element

### ISSUE THREAD

**Issue by lwasser** [ropensci/EML#140]
HI @cboettig - i'm running into another error with another EML file. 

When i try to read with `read_eml()` i get the error
```
Error in metaclasses[[s]] : attempt to select less than one element
```

can you please help me understand what this error means? I did notice that the indentation / hierarchy of the file is a bit unusual - could that result in this error?

The file:
https://github.com/NEONInc/neon-eml/blob/master/neon_eml_components/NEON_EML_Boilerplate.xml

Thank you!

**Comment by cboettig** [comment]
@lwasser hmm, sounds like a bug, but I'm getting a 404 on the link to the file.  Have you checked that the file is valid? (Note that `eml_validate()` can take a file name as an argument, so it's not necessary to run `eml_read()` in order to validate the file.)

**Comment by lwasser** [comment]
Hi @cboettig maybe the repo is private? I just uploaded it here

https://github.com/lwasser/testRep/blob/master/NEON_EML_Boilerplate.xml

But here is the message i get for EML_validate when i open the file locally
```
# this doesn't open - format issue?
eml_NEON <- read_eml("~/Documents/Github/neon-eml/neon_eml_components/NEON_EML_Boilerplate.xml")
```

## Response:
```
Error in metaclasses[[s]] : attempt to select less than one element
```
## Code:
```
eml_validate("~/Documents/Github/neon-eml/neon_eml_components/NEON_EML_Boilerplate.xml")
```
## Response:
```
$status
[1] 1871

$errors
[[1]]
$msg
[1] "Element 'creator': This element is not expected. Expected is one of ( references, alternateIdentifier, shortName, title ).\n"

$code
XML_SCHEMAV_ELEMENT_CONTENT 
                       1871 

$domain
XML_FROM_SCHEMASV 
               17 

$line
[1] 13

$col
[1] 0

$level
XML_ERR_ERROR 
            2 

```

$filename
[1] "/Users/lwasser/Documents/Github/neon-eml/neon_eml_components/NEON_EML_Boilerplate.xml"

attr(,"class")
[1] "XMLError"

attr(,"class")
[1] "XMLStructuredErrorList"

attr(,"class")
[1] "XMLSchemaValidationResults"

**Comment by cboettig** [comment]
Yup, the repo you linked is probably private, so I cannot see the file.  please feel free to attach the file to this issue and I'll take a look at it.

It does look like the eml file is not valid though, which might be part of the reason why `read_eml()` cannot parse it (though even some invalid eml should still parse, so probably a bug on my end).

**Comment by cboettig** [comment]
whoops, I didn't see you had a new link there.  Great, I'll take a look and see what's up.

**Comment by lwasser** [comment]
I just emailed you the file as well. Github doesn't seem to approve of attaching .eml files to an issue!

**Comment by cboettig** [comment]
Thanks.  Re the validity issue, the error msg is telling you, all be it crypically, why it's not valid:

```
[1] "Element 'creator': This element is not expected. Expected is one of ( references, alternateIdentifier, shortName, title ).\n"
```

If you look at the XML, you'll see the first child element to your `dataset` is `creator`.  A `title` is a required field which is missing from your document, and has to come before a `creator` in EML.  (If you look at [this diagram](https://github.com/ropensci/EML/blob/master/inst/xsd/docs/eml-2.1.1/eml-dataset.png), you can see that a ResourceGroup has the optional elements `alternateIdentifier` and `shortName`, then the required element `title`, all before the `creator`; hence the error msg).  Looks like there are other errors in which elements are in the wrong order as well (language, maybe others)

Unfortunately, the Schema validator stops at the first error, and it looks like there are other errors in the document that are responsible for the `read_eml` to fail.  In particular, that failure is I believe because the `citation` element has a child element `online` that really should be inside a `distribution` element, like so:

```xml
<distribution>
  <online>
    <url>http://www.neoninc.org/sites/default/files/basic-page-files/NEON_Strategy_2011u2_0.pdf</url>
  </online>
</distribution>
</citation>
```

With that change it can parse. (`read_eml()` can deal with invalid order, but here it tries to put an `online` item into a `citation` object which doesn't have a slot called `online`, so it fails.  We should probably figure  out how to at least give a coherent error message in that case.)

**Comment by lwasser** [comment]
Ok - thank you @cboettig I've been doing some reading on the specifications.

1. the above fixed import! no error on import if i add

```
<distribution></distribution>
```

2. the old version of the eml package imported the file anyway - no error even without `distribution`.

3. my question - is the `distribution` element in the eml specs? i had a hard time finding / understanding how I would know to add the distribution element before <online> in the documentation on the knb website. Is this a @mbjones question?

**Comment by cboettig** [comment]
@lwasser yes, the `distribution` element is in the official EML spec, though I completely agree with you that it is not at all obvious!  I'm hoping that if you created your boilerplate document with the R package it would help make it easier to figure this out and harder to make this mistake!  For instance, if you were creating a citation in the R package, you might do: `getSlots("citation")` and see it has a slot for `ResourceGroup`, and `getSlots("ResourceGroup")` and see it has a slot for `distribution`; while it wouldn't be possible to accidentally add the url without putting it into a `distribution` element.


Re the official specs, you can see it in the png I linked for the `dataset` object, though you cannot see what it contains.  In the actual official documentation for the dataset, you can see it listed under the parts of a `dataset`: https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/./eml-dataset.html#DatasetType .  which lists the following slots for a dataset:

```
DatasetType 

Content of this field:	Description of this field:
Elements:	Use:	How many:
A choice of (
A sequence of (
res:ResourceGroup	 	 
purpose	optional	
maintenance	optional	
contact	required	unbounded
publisher	optional	
pubPlace	optional	
methods	optional	
project	optional	
A choice of (
dataTable	required	
OR
spatialRaster	required	
OR
spatialVector	required	
OR
storedProcedure	required	
OR
view	required	
OR
otherEntity	required	
)
)
OR
res:ReferencesGroup	 	 
)
Attributes:	Use:	Default Value:
id	optional
system	optional
scope	optional	document

Content of this field:	Description of this field:
Elements:	Use:	How many:
A sequence of (
description	required	
maintenanceUpdateFrequency	optional	
changeHistory	optional	unbounded
)
```

Note that at the top it refers to a "ResourceGroup".  This is part of my point to @mbjones in #141 : if you want to know how this stuff is defined, these docs seem to be the definitive reference, and they do indeed refer to things like "ResourceGroup" rather than listing the slots.  (The copy-paste above isn't very readable, but follow the link above to go to the actual docs).  If you then click through on "ResourceGroup", you see how it is defined: https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/./eml-resource.html#ResourceGroup


where it has a list of slots, including one called "distribution".  If you click on that, you'll see the options for online type, etc.  


I completely agree with you that this isn't obvious.  I'm hoping to add more documentation & higher-level functions to the package that can help; guess we'll see how that goes...

**Comment by mbjones** [comment]
Sorry if the EML docs are confusing. Mea culpa.  But, in my defense, its actually a pretty extensive vocabulary with lots of options and depth, and it was hard to find a simple way to document it.  The XSD files are the definitive source of info, and it should be extremely clear from the XSD files what is required where and when.  The HTML documentation of the spec is generated from the XSD files, and is meant to be more human readable.  It was developed using early 2000's web tech, so no doubt it could be improved today, especially in terms of display and navigation.  We'd welcome contributions if anyone wants to improve HTML docs generation from the schemas.  The PNG images were meant to give an overview of what is in the HTML docs, but we have each of them show only what is directly defined in that module, to keep the images manageable in size. 

For this particular case, when the docs for `DatasetType` list `res:ResourceGroup` in the list of elements, you must follow that link to understand what is included from ResourceGroup. We assume (probably wrongly) that anyone reading the EML specification understands how XML and XML Schema languages work, and [Model Groups](https://www.w3.org/TR/2001/REC-xmlschema-1-20010502/#cModel_Group_Definitions) are a formal structure in XSD that can't just be ignored.  Once you look at `ResourceGroup`, you will immediately see that it includes `distribution` as an element, which is also shown in the [image for the eml-resource module](https://knb.ecoinformatics.org/emlparser/docs/eml-2.1.1/eml-resource.png).  We will gladly accept PRs for documentation improvements in EML, and I could move EML to github if that would make it easier.

**Comment by cboettig** [comment]
@mbjones didn't mean to complain, your right that EML kinda has to be complex to handle the use cases.  I am curious about how you think we should be thinking about Model Groups though, since that's closely related to the question in #141.  Based on your and @lwasser feedback it sounds like we in some way do want to gloss over Model Groups; e.g. avoid a class representation for "ResourceGroup" etc and just stick those slots in `dataset`.  

I suppose the documentation equivalent would be to have the documentation for `dataset` object show the slots the way the XML looks, e.g. just listing all the elements in resource group directly, rather than showing the way the schema works, where it just says that a `dataset` contains a `ResourceGroup` of slots.  It might mean a little less clicking that way (e.g. you go right to the documentation of `dataset`, instead of clicking on `DatasetType` and then `ResourceGroup`.    I'm not sure if that would actually improve the docs or not; I suppose it could also cause trouble.  

(because the R code is generated programmatically from the schema to start with, it does what the docs do and reflects the way the schema looks, where we have S4 classes for all Model Groups (yes, we have class for `dataset` that inherits from the S4 class `DatasetType`).

**Comment by mbjones** [comment]
@cboettig I think there are different use cases.  The EML specification is meant to accurately reflect the XSD schema, as it documents how the schema works.  In the end, its not probably the best end-user documentation, but is useful for anyone trying to understand the EML XSD files.  We could really use some better end-user docs, and those I think should gloss the Model Group constructs, as those are purely schema shortcuts.  Ultimately, a `dataset` element must contain a `title` preceding the `creator`, and this is what end user's need to know -- they follow the XML structure.

One way to really improve this in the EML R package would be to add validation code to each class, such that it would be easy for a user to `validate(dataset)` and get nice human readable error messages such as `dataset@title is NA and must be provided`.  We do this type of validation in Morpho by turning fields red when required fields are missing.  Maybe the print() function for each class could show the slot structure and highlight required slots that are missing in some way that makes it obvious (boldfacing, strikethough, etc.)? Then if one did a print(eml_doc) from the top level, the whole hierarchical structure would recursively print out, showing validation errors in the whole XML tree.  Quite a lot of work, but probably useful.

**Comment by cboettig** [comment]
Yup, agree that would ultimately be very nice; maybe open an issue for that?  

I also like the suggestion that the print structure should print required but missing elements.  (Might be harder to signal if elements are out of order.  & Of course consistent color feedback in a terminal can be tricky, though Gabor's done wonders with https://github.com/gaborcsardi/crayon ).  

Meanwhile, you can hack something pretty close to this already; if I just work out the namespace a bit, one could then call eml_validate() on any S4 object and see what the schema validator says.  

Overall though, I am hoping as much as possible to simply make it less likely that user generates invalid EML in the first place, rather than find ways of warning the user after the fact.  For instance, if you just use the `new("dataset", creator=creator, title = title)`, EML will automatically get the order right and a user doesn't have to worry about that in the first place.

**Comment by cboettig** [comment]
Looks like we've hit upon several new issues in this thread, so adding them as new issues so I don't lose track.  Meanwhile I think we've resolved the bug here and the funny notation problem.
