### ISSUE TITLE
What are factors related to a spatial dataset? - set_attributes()

### ISSUE THREAD

**Issue by lwasser** [ropensci/EML#142]
Hi @cboettig  -- ok i'm trying to create my own EML file using the package for one of our AOP datasets given that's the IPT i work on now. I'm running into issues with  `set_attributes`. It requires a `factor` element however i don't understand how that relates to the attributes of a raster. IN this case, the raster is reflectabce. the values are 0-10000 with a scale factor of .0001 as defined in the EML specs. What should i enter for factors? I tried NA and NULL as values but set_attributes doesn't seem to work. if i leave factors out, i get an error.

`Error in set_attribute(attributes[i, ], factors = factors) :  object 'node' not found`

```
# create first raster object
attributes <-
data.frame(
  attributeName = "Reflectance",
   attributeDefinition = "At sensor reflectance.",
  measurementScale="unitless",
  accuracy=".5 meters",
  stringsAsFactors = FALSE
)

attributeList <- set_attributes(attributes,
                                factors=NULL)

raster1 <- new("spatialRaster",
               EntityGroup= myEntityGroup)
raster1
```

**Comment by cboettig** [comment]
whoopsies, that's a bug!  You should be able to leave factors out if you don't have factor (enumeratedDomain) data. fixing now.

**Comment by cboettig** [comment]
(Also just a note that as per your and @mbjones advice in #141, I'm looking to eliminate those metagroups, so there won't be a `new("spatialRaster", EntityGroup = mygroup` any more, you'll have to spell out each of those slots).

**Comment by lwasser** [comment]
perfect. Thank you for fixing this! :)

Re: the new approach? Will that allow for increased flexibility in terms of adding potentially yet to be defined attributes? (custom attributes).

What would that look like in terms of syntax? Per the spec, you need to have either dataTable, spatialRaster or spatialVector .

**Comment by cboettig** [comment]
Not sure I follow.   Re #141 issue, this just means that declaring and accessing slots should work just the way it looks in the XML.  e.g. in a dataset you see:

```xml
<dataset>
  <title>My title</title>
```
and thus the R will now use the more intuitive: `dataset@title` to access and the `new(dataset, title = MyTitle")` to create, instead of the `dataset@ResourceGroup@title` and `new(dataset, ResourceGroup = new('ResourceGroup', title = "my title"))`.  Same for `EntityGroup`.  


Re custom attributes, I'm not sure what you mean.  

Right, a `dataset` can contain either a dataTable, spatialRaster, spatialVector, storedProcedure, view, or otherEntity.    You can always create a second eml to have another dataset with a different type though.  hmm, I don't think I'm following what you're trying to do here.

**Comment by cboettig** [comment]
@lwasser sorry didn't mean to close, just meant that I'd fixed the `factors` bug.  Just close this when you're ready.

**Comment by lwasser** [comment]
@cboettig no problem. I also understand wanting to close / address issues! i made my question too complicated. i just want to understand how to code this now with the changes in place

```
raster1 <- new("spatialRaster",
               title = "Reflectance", 
               abstract = "At ground reflectance - more description needed.")
```

i get the error:
```
Error in .local(.Object, ...) : 
  unused arguments (title = "Reflectance", abstract = "At ground reflectance - more description needed.")
```

(i tried name and description as well and got the same error).
I am able to now access the slot `@coverage` directly which is nice.

The factor issue seems to still be coming up. I reinstalled EML and restarted R. is this another case of user error?

```
myEntityGroup <- set_EntityGroup(name = "Reflectance", 
                               description = "At ground reflectance - more 
                               description needed.")
```
returns the error that it can't find the `set_EntityGroup()` function. 

Perhaps i'm jumping the gun as you're still implementing changes? I can revisit this again next week if that would be better!

**Comment by cboettig** [comment]
@lwasser Um, spatialRaster doesn't have slots called `title` and `abstract`.  (Those belong to objects that contain "ResourceGroup", not objects that contain an "EntityGroup", but since we closed #141 you can forget that complexity).

Do `getSlots("spatialRaster")` and you'll see what slots it has.  It has something called `entityName` and `entityDescription`, which might be what you are looking for:

```r
raster1 <- new("spatialRaster",
               entityName = "Reflectance", 
               entityDescription = "At ground reflectance - more description needed.")
```

`set_EntityGroup` is now `set_physical`.  `set_physical` is a helper function that is really geared towards creating documentation of CSV files at the moment, rather than spatialRaster data, but it really isn't doing anything too fancy.  Really the only reason `set_physical` exists (and maybe should be renamed) is to help the user find a simple function which documents all the common options used in document the CSV and other tabular data formats.  

In some ways the `set_` methods are all a bit redundant, because you can just call `new("myclass", slot1 = stuff, slot2 = new("slot2", stuff) ...` etc to construct arbitrary eml.  My thinking is that the `set_` methods compromise a bit of that flexibility in exchange for something that is a bit easier to use and covers common cases.  

So far I've focused on tabular data since that's what I'm most familiar with.  You may be able to help me come up with some good `set_` methods to work with spatial data.  

In my opinion, it would be ideal for the spatial methods to be based around some R spatial data classes like `sp`.  I've done a similar version of this in regards to the literature classes already, though it needs testing. -- you should be able to read a bibtex file into R and get R's bibentry objects (that does work -- in fact you can use RefManageR and import these using dois instead), and then just do: `as(ref, "citation")` to get an EML citation object you can use in EML elements. (Actually you can skip the `as` part and just pass them to the `new` method, which will do that bit for you).

**Comment by cboettig** [comment]
@lwasser Think we ready to close this?  Would be great if you could take a look at the draft vignette on creating EML (#145), which might also address some of the questions you highlight here.  Feel free to open new issues for anything that arose in this thread that we didn't get to yet.

**Comment by lwasser** [comment]
Yes - let's close it! I'll check out the vignette!!
