### ISSUE TITLE
Vignette on Publishing EML

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#146]
As I've mentioned before, I think a killer app of EML is publishing to a metacat repo, and really want to add an example of this as a vignette.  In particular, this should show how the EML metadata then becomes searchable, and hopefully show also how to use EML in a 'controlled access' setting, where a user grants access to specific collaborators.  

My hope is to illustrate how an individual lab group could thus start using these tools to manage their own data in a secure, backed-up, and searchable environment.  In this context, it is the producers of the metadata who are the primary users of that metadata, which I think helps incentive them to create more thorough and consistent metadata (as they benefit directly, instead of just altruistically helping their ... competitors ...) .  Once data has been properly annotated and archived privately it is then (hopefully) just the flip of a switch to make it public once the researchers feel comfortable doing so.  

This should ideally also address 'living data' files, or how a metadata file should be updated and re-uploaded as data grows & evolves.

@mbjones  Does this sound reasonable?  Is the `dataone` package ready for this kind of application (e.g. via KNB)?  Would that access control still be set by EML `access` nodes, or is that controlled at the DataONE or other level?

**Comment by mbjones** [comment]
@cboettig More than reasonable, this sounds great!  Its exactly the use case we are trying to enable, and the dataone package is ready to handle all of the upload bits, as well as collate the data and metadata, make resource maps and system metadata, and handle other housekeeping.  Access control is handled in DataONE now via the SystemMetadata document associated with each object, rather than EML -- this was changed so that we could equitably support not just EML, but also ISO, FGDC, etc. We've written an initial [vignette describing the dataone upload process](https://github.com/DataONEorg/rdataone/blob/master/vignettes/upload-data.Rmd), and step 2 is where the EML package could really shine. The example we wrote is to a development server, but the KNB could be substituted just as easily.

**Comment by ivanhanigan** [comment]
I agree with you that it will be a killer app to "illustrate how a lab group could use these tools to manage their own data in a secure, backed-up, and searchable environment", " to create more thorough and consistent metadata (as they benefit directly, instead of just altruistically helping their ... competitors ...)".

WRT `rdataone` package... is what @mbjones describes going to be easy for anybody with a metacat portal or only with KNB as the target? For ie could I deploy metacat for me and my mates on amazon or some VM at my university and use this for the lab's data warehouse and documentation?

**Comment by mbjones** [comment]
The `dataone` package can be used against any Metacat instance that has enabled the DataONE API in the configuration.  That said, there will be some authentication issues for standalone Metacat instances, in that the Metacat admin will need to work out how to issue authentication tokens, as this is something that is currently handled by DataONE itself.  One of the services DataONE provides is a global user namespace that spans many data repositories and allows logins via universities, Google and ORCID.  A standalone Metacat would need to replace this infrastructure in a way that both the R client and Metacat understand (namely, by issuing JWT auth tokens that the Metacat instance is configured to trust).

**Comment by cboettig** [comment]
**development note** this has been started here: https://github.com/ropensci/EML/blob/master/inst/examples/metadata-repositories.Rmd , but stalled at the moment due to possible bugs or user errors preventing me from actually getting the private sharing working on the DataONE dev server, see: https://github.com/DataONEorg/rdataone/issues/138

**Comment by mbjones** [comment]
@cboettig  That's great. Thanks.  We're releasing a new repo this week, but
will get back to you with trying to figure out why your access control
rules aren't working.

Also, in your DOI section at the bottom, a quick note:  in addition to
giving the new DOI to the `new()` API call, you should also be setting it
as the `eml@packageId` in your `sampleEML` file.

**Comment by cboettig** [comment]
@mbjones thanks, yeah, I was a bit unclear on where it was best to use a DOI identifier.  So does that also mean that the the `packageId` returned by `uploadDataPackage` is the one given as `packageId` in the EML?  

So even if we aren't using DOIs, like in the example further up, it would be ideal to set the metadata identifier to the value it has in `eml@packageId`?  (also if so, not sure how that generalizes to other metadata since I'm not familiar with the other standards, though presumably they also have package identifiers).

**Comment by mbjones** [comment]
Yeah,in general, the eml@packageId should match the identifier used for the create() or update() call that transfers it to DataONE (and it should match in the associated SystemMetadata as well.  Unfortunately, metadata standards have lots of ways of representing these id concepts, so we put the identifier in SystemMetadata to be totally clear and consistent.  The REST API uses the id as the key for what is being manipulated, and should fail if the ID does not agree with what is in SystemMetadata.  But, because 1) the md standardards are all over the place on IDs, and 2) we don't know what md standards will be added to the system, we don't do any consistency checking in the science metadata -- that's up to the user.  But it would be very odd to display identifier 'X1' from SystemMetadata and show the EML document with identifier 'Y1' -- so the user needs to be consistent.  It would be nice to streamline this, but I think its a casualty of supporting many metadata standards that are in use.
