### ISSUE TITLE
"eml_get" method that need not assume much knowledge of the EML schema

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#153]
A command like: 

``` r
get_attributes(eml_HARV@dataset@dataTable[[3]]@attributeList)
```

assumes the user is familiar enough with EML schema to construct the above S4 path to the desired element.  While this is a useful low-level function, it is not exactly a user friendly design.  I think we should have a higher-level function that would find all `attributeList` elements regardless of where they appear in the EML document and return them (e.g. returning a list of results when there are multiple `attributeList` elements, as in @lwasser 's example above).  

@mbjones curious what you think of this and how to do it 'safely'?  e.g. while it would simplify calls such as above into:

``` r
## gets all attributeLists:
all <- eml_get(eml_HARV, "attributeList")

all[[3]] # just the attribute list for the 3rd dataTable
```

a thoughtless user might call something like `eml_get(eml, "creator")` and get `creator` elements from all over the EML file, but mistake them for being creator elements belonging to the top level (e.g. eml@dataset@creator elements).  

In general I know the nested structure is always potentially meaningful, but I do think this kind of 'find all' functionality would help.  Maybe it would be better to call the method `find_all()` than `eml_get`?

**Comment by mbjones** [comment]
@cboettig I agree that the higher-level functions are needed for usability.  Its awesome that the low-level ones are now complete in their coverage of EML.  We're in so much better of a situation to build a highly usable package.

I think some targeted accessors would be the best bet, rather than the general-purpose `eml_get`.  For example, for data entities and attributes, what a user really needs to be able to do is find out how many data entities there are, what their types are, and be able to then get the attribute list for one or more of these.  So, what do you tink of a set of functions like this:

```R
## get the list of data entities
data_list <- eml_data_entities(eml_HARV)
att_list <- eml_data_attributes(data_list[3])
```

The return type of the first function would be a list of entities, so those could be manipulated directly as desired.  The return type of the second function would be a list of attributes, which also could be manipulated as needed. 

Both the entity and attribute types should have nice, pretty printing functions so that, if someone calls `print(data_list[3])` they get a nicely formatted view of that entity's metadata (including its attribute list), and if someone calls `print(att_list)` or `print(att_list[4])` they get a pretty-printed view of the attribute or list.

```R
> print(data_list[3])

EntityName: Tundra Temperature Anomaly Data
ObjectName: tundra-anomaly.csv
EntityDescription: Month-to-month anomalies in temperature at the tundra surface from 1978.
EntityType: DelimitedText File (sep=',', escape='\', quote='"')
Attributes:
    name    type       units           description
    site    character  --              Name of the site
    date    date       YYYY-MM-DD      Date on which the temperature was measured
    temp    numeric    degreesCelsius  The temperature measured at the site on the given date
    anom    numeric    degreesCelsius  The temperature anomaly from the ten year average
```

In addition, then we would be be able to modify these metadata structures and reassign them back to the original eml document without the super-long XPath knowledge.  For example, `att_list[1]@name <- 'sitename' would be much easier than the long paths down through the EML.

Would love to discuss this further.

**Comment by cboettig** [comment]
@mbjones Thanks, this sounds great.  The first part of this is straight forward, it's mostly a semantic or UI question of whether it's better to have one function `find_all(eml_HARV, "dataTable")` vs separate functions like `find_all_dataTable(eml_HARV)`.  I've implemented the former now, which is convenient since it automatically covers any EML element, not just the ones I've written functions for.

I'm a bit confused about terminology -- you refer above to `data_entities` and `data_attributes`; my inclination is to stick with the vocabulary that EML uses -- i.e. I think you are referring to `dataTable` elements and `attributeList` element from those `dataTable` elements, but not quite sure.   (likewise your example attribute table columns don't necessarily have an obvious single mapping to the EML; e.g. you've put a `formatString` value in a `unit`, and it's not clear in the case of a `character` type if `description` is `attributeDescription` or `textDomain/description`.  We've worked out a `data.frame` representation of an `attributeList` already in `get_attributes()` function, but that has 17 possible columns -- hard to pretty print -- plus a separate table for factors).  


I think things get much harder when we start to think about the pretty print method.  First, I'm wary of defining this as the default S4 object `show` method for, say, `dataTable` objects, because I think that will confuse users when lots of information contained in the object does not appear in the `show`.  It would make more sense to define a method named `head` or `summary` for this purpose, to make it clear that what is being shown is just the most useful of information.  

I'm also worried about making the same mistake I made with the first iteration of EML by defining constructs that make a lot of assumptions about the EML file that may or may not hold.  e.g. the mock-up you show makes sense for a dataTable with one `physical` element, but of course in theory there can be multiple (and of course it assumes simpleDelimitedText etc).  It's easy to write something that does this for data that looks like what you show, it's just not clear how this method should behave in the general case.  


Regarding your last comment about modifying metadata structures, that already works to some extent in our S4 construction, because it's already modular.  You can start defining some element (say, an `<attribute>` or `<physical>` and just add it to it's parent node later; you don't have to start by creating an `eml` object and referencing everything all the way down the path from the root node.  I think this should be clear from the [Creating EML](http://ropensci.github.io/EML/creating-EML.html) Vignette (see #145)?    Or maybe you have something else in mind here?

**Comment by mbjones** [comment]
@cboettig 'Entity' is the generic term in EML that we use to generically represent data tables, spatial rasters and vectors, and other types of data structures.  It is defined in [eml-entity](https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/index.html#N1014A), and provides the `EntityGroup` structure that includes all of the elements that are common to different entity types.  It would be great if the EML package in R dealt not just with dataTable but also with other types of entities such as spatialRaster, spatialVector, and otherEntity.

I agree that it might be dangerous to omit metadata in show() or print(), but at the same time its really critical for users to get an overview of the metadata in a much more compact form than would be possible by showing the actual class/slot structures.  I'd love to discuss this more in terms of what would be useful.

**Comment by cboettig** [comment]
@mbjones Thanks, right, I'm familiar with `EntityGroup`, just wasn't sure if that's what you meant.  EML does deal with all of these, it is just a question of figuring out what behavior we want for each and what syntax we want for that behavior. 

Do you feel it would be useful to have a function like `eml_data_entity()` that returns whichever entities exist, regardless of their type?  If so, what is the desired behavior for each type?  (Or the desired behavior for the associated summary function)?  We can figure all that out, but I think your way ahead of me.  

Right now, I'm working on something a bit more basic.  With the current implementation of `eml_get()`, you could extract all the `dataTable` objects, a user could pretty easily request the information you display:

```r
eml_HARV <- read_eml("http://harvardforest.fas.harvard.edu/data/eml/hf001.xml")
# Get all dataTable entities
dt <- eml_get(eml_HARV, "dataTable")

## Get their attribute tables, as `data.frame`s:
attrs <- eml_get(dt, "attributeList") 
```

Note that in this second example, it finds a dedicated method for `attributeList` types, which returns the data.frame, otherwise it just returns the S4 object (whose print method uses the XML format for now, which seems like an intuitive choice but I'm open to suggestions). Of course if the element just contains a string (e.g. can be coerced to a character) than `sapply` will return the character string directly, as in: 


```r
## Get specific information from `dt`, such as `url` for downloading:
urls <- sapply(dt, eml_get, "url")

```

Compare this last operation to the lower-level way (formerly the only way) to do this:

```r
urls <- sapply(dt, function(x) x@physical[[1]]@distribution[[1]]@online@url)
```

Clearly the `eml_get` method is a lot more concise than writing out that anonymous function and all the subsetting (particularly when repeated elements can occur, like in `physical` and `distribution`).  Now obviously the `eml_get()` method has the potential to return irrelevant information, because it could encounter a `url` somewhere else in the `dataTable` entity; though for interactive use at least I don't think this is a big issue.  (In practice there are lots of elements that are uniquely identified by their element name even though they need a verbose full path to specify them).  If necessary, a user could always repeat the call to first get a lower element (e.g. to exclude `url`s that appear somewhere other than in the `physical` node: 

```r
physical <- sapply(dt, eml_get, "physical")
sapply(physical, eml_get, "url")
```

Anyway, very curious what you think of this approach.  is this kind of syntax for `eml_get()` helpful?  Would the method be better named `find_all()` or something like that?

**Comment by mbjones** [comment]
I think we're on the same page.  `eml_get()` does seem really useful, and I think we should keep it for power users that already know and understand the structure of an EML document and the names of key elements.  The problem is, `eml_get()` as a function gives no guidance to the user as to how to get critical information out of an EML document.  Which is why I am suggesting some specific helper functions that utilize eml_get internally, but target key parts of the EML document.  While a complete oversimplification, I think the crux of all EML documents resides in a few key structures:

- Overall package bibliographic identification (packageId, title, creators, abstract, ...)
- Coverage
    - Spatial
    - Temporal
    - Taxonomic
- Data entities (1 or more, of any type (dataTable, spatialRaster, spatialVector, otherEntity)
    - Attribute lists (for some data entities)
- Methods
- Project metadata (id, title, PIs, funding info)

We can quibble over what's critical, but I'd like to see accessor methods that make it obvious to R users that this structure exists, and that give a named method to show and modify the main parts of this tree.  Maybe these would be functions like `eml_get_spcov()` that would both return the relevant subtree or list of subtrees, but also that prints the structure for review.  Or maybe they are just summary display functions like `eml_show_spcov()` or `eml_show_data()`. In any case, I think getting the summary is key, as is not overburdening the user with a massive tree structure, and easy, obvious parallels with the eml classes are needed so people know how to make changes.  These are navigation and exploration functions for people who know nothing about EML, but might have read in a 2000 line EML document and are overwhelmed by pages of XML output or a massive tree-base listing of slots that scrolls up and off of their R terminal buffer.  I stand by my desire for summary/tabular printouts shown in the comments above, although I agree we'd want to talk through the details of units, etc to make them both compact but also not misleading.

**Comment by cboettig** [comment]
Awesome, yup, agree entirely with this view.  And thanks for the outline
above; figuring out what to focus on & what to omit is the crux of the
matter; and the above list is a good starting point.

This is basically along the lines I've already started with dedicated set_
and get_ methods for coverage (and it's three components), attributeList,
and so forth.  We should probably discuss each in its own issue, and add
issues for those that don't have them.

But the devil is in the details here.  For some/many of these I think there
is an intermediate step needed.  For instance, that is what we have in
get_attributes(); it returns a data.frame with 17 columns.  A pretty print
method would drop columns that were all NA (and maybe ignore certain
columns all together), but that would make the function more fragile to
program with even while making it pretty print.

These issues are also arise in the set_ methods.  For instance,
set_coverage (or set_taxonomicCoverage ) takes a list of (space-separated)
scientific names, which is common and simple.  However, I couldn't write a
corresponding get_taxonomicCoverage that returns a list of species names,
since of course we cannot assume that taxonomicCoverage includes genus &
species (made harder since rank appears to be freeform text, so we see
variation in GENUS vs genus etc).

I'm sure you & team already given much more thought into how to construct
these simplified or lossy conversions of full EML into something simpler
that users can quickly grok, like you say. Do you have good examples you
can point me to?   I guess looking at "optional" vs "required" fields is
some help, but feels kinda like we're defining an EML-lite schema in the
process here.

On Tue, Mar 22, 2016, 7:04 PM Matt Jones <notifications@github.com> wrote:

> I think we're on the same page. eml_get() does seem really useful, and I
> think we should keep it for power users that already know and understand
> the structure of an EML document and the names of key elements. The problem
> is, eml_get() as a function gives no guidance to the user as to how to
> get critical information out of an EML document. Which is why I am
> suggesting some specific helper functions that utilize eml_get internally,
> but target key parts of the EML document. While a complete
> oversimplification, I think the crux of all EML documents resides in a few
> key structures:
>
>    - Overall package bibliographic identification (packageId, title,
>    creators, abstract, ...)
>    - Coverage
>       - Spatial
>       - Temporal
>       - Taxonomic
>    - Data entities (1 or more, of any type (dataTable, spatialRaster,
>    spatialVector, otherEntity)
>       - Attribute lists (for some data entities)
>    - Methods
>    - Project metadata (id, title, PIs, funding info)
>
> We can quibble over what's critical, but I'd like to see accessor methods
> that make it obvious to R users that this structure exists, and that give a
> named method to show and modify the main parts of this tree. Maybe these
> would be functions like eml_get_spcov() that would both return the
> relevant subtree or list of subtrees, but also that prints the structure
> for review. Or maybe they are just summary display functions like
> eml_show_spcov() or eml_show_data(). In any case, I think getting the
> summary is key, as is not overburdening the user with a massive tree
> structure, and easy, obvious parallels with the eml classes are needed so
> people know how to make changes. These are navigation and exploration
> functions for people who know nothing about EML, but might have read in a
> 2000 line EML document and are overwhelmed by pages of XML output or a
> massive tree-base listing of slots that scrolls up and off of their R
> terminal buffer. I stand by my desire for summary/tabular printouts shown
> in the comments above, although I agree we'd want to talk through the
> details of units, etc to make them both compact but also not misleading.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/EML/issues/153#issuecomment-200129058>
>
-- 

http://carlboettiger.info

**Comment by cboettig** [comment]
This thread identified the need for specific high-level `get` and `set` methods

- [ ] Overall package bibliographic identification (packageId, title, creators, abstract, ...)

- [ ] Project metadata (id, title, PIs, funding info). _not quite sure what this refers to / how it differs from the above_

- [ ] Coverage `set_coverage` but no `get_coverage` with pretty-printing
  - [ ] Geographic `set` method only so far
  - [ ] Temporal `set` method only so far
  - [ ] Taxonomic has `get` and `set` methods, but also raises some challenges (e.g. output of get_taxonomicCoverage is of a different data structure than input of `set_taxonomicCoverage`)

- [ ] Data entities (1 or more, of any type 
  - [x] dataTable,   This is pretty much covered with the generic methods plus the existing custom functions: `get_attributes` and `set_attributes()` and `set_physical()`, see the vignette.  
  - [ ] spatialRaster, 
  - [ ] spatialVector, 
  - [ ] otherEntity


- [x] Attribute lists (for some data entities) _implemented already in `get_attributes()` and `set_attributes()`  (but see #151 for ideas to improve).

- [x] Methods  _implemented already in `set_methods()`, with help by using external (e.g. Word docs) with `set_TextType()` (but see #149, #137, #158).  Do we need a `get_method()`?

**Comment by masalmon** [comment]
(I hope I'm not missing this having been already discussed/already exists -- I'm slowly re-reading issues :grin:) I have a question regarding `get_attributes`. In a eml with several `dataTable`, if I use `eml_get(eml, "attributeList")` I get a list with no names. I wonder if it should use the names from `entityName`. Maybe an easier-to-use version would:

* `get_attributes(eml)` returns the list of lists, but with names corresponding to `entityName`'s.

* `get_attributes(eml, entityName = "pm25")` returns the list for `pm25` only. I can obtain something similar using 

```r
dt <- eml_get(eml, "dataTable")
attrs <- eml_get(dt[[1]], "attributeList") 
```
but maybe it'd be easier with `entityName` instead of index?

**Comment by cboettig** [comment]
This structure is somewhat more transparent in the S3 structure, print methods, and get_* and  set_* methods of the revised EML package.
