### ISSUE TITLE
Feedback improving set_section method and documentation

### ISSUE THREAD

**Issue by cgries** [ropensci/EML#158]
I think, in the set_section function the file.copy method needs an overwrite = TRUE, it currently doesn't replace an existing file in the temp directory with an updated copy. 
Some documentation that the Word file needs to have a title and at least one paragraph of text would be very helpful. Having just a paragraph of text in that file lets the line
 
sections <- XML::xpathApply(docbook, "/article/sect1", XML::xmlChildren)

fail, because a single paragraph without title is converted to this dockbook format without a sect1 element:
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">
<article>
  <articleinfo>
    <title/>
  </articleinfo>
  <para>
  See abstract for detailed method description
</para>
</article>

**Comment by cgries** [comment]
On second thought, the docbook issue described above is not a documentation issue but a programming. It is legitimate in EML to enter only a single paragraph of text with the <para> element only, without a title and <section>.

**Comment by cboettig** [comment]
Thanks for catching this, and I agree that this is something we should be handling internally in the code.  I'll take a look and see how we can work around that.  

In general `set_section` is a little more fragile than I would like, mostly because we are leveraging pandoc to convert directly to docbook, while EML doesn't support the full implementation of docbook. So users doing anything a bit fancy in Word may run into trouble with invalid EML.  Not sure what the best way around that is either, but open to suggestions (see #137)

**Comment by cboettig** [comment]
@cgries okay, just pushed a fix for this in 4792d3e, but it does change the API slightly.  Now instead of calling `set_section()` on a document, you call set_TextType, which is more generic.  EML TextType elements (like abstract, description, methods, etc) can have either `para` or `section` child elements -- it seems pandoc creates the latter in docbook when a title element is present, but the former when it is not. For instance, compare:

```r
## Can also import from methods written in a .docx MS Word file.
f <- system.file("examples/hf205-abstract.docx", package = "EML")
a <- set_TextType(f)
as(a, "abstract")

## Documents can have richer formatting.  Documents with title headings use `section` instead of `para` notation
f <- system.file("examples/hf205-methods.docx", package = "EML")
d <- set_TextType(f)
as(d, "description")
```

For very simple text a user can sidestep the external document all together, which forgoes any docbook formatting, i.e.;

```r
a <- set_TextType(text = "This is the abstract")
as(a, "abstract")
```

I've also updated the vignette to reflect that the suggested pattern is now to create a TextType element using `set_TextType` and then coerce it into the desired element using `as`, as in the above examples. (A user can confirm that, say, `is(new('abstract'), "TextType")`).  

Not sure if this approach is too low level or not -- any suggestions to make the user interface less clunky are welcome! also cc @mbjones .

**Comment by cgries** [comment]
@cboettig  works great, thanks for fixing that. 

The code in `set_TextType` still doesn't overwrite the temp file when I update the original file containing any of this information (e.g., IntellectualRights, abstract, methods).

**Comment by cboettig** [comment]
Oh right, forgot about that part, thanks for the reminder

On Fri, Jun 17, 2016, 8:59 AM Corinna <notifications@github.com> wrote:

> @cboettig <https://github.com/cboettig> works great, thanks for fixing
> that.
>
> The code in set_TextType still doesn't overwrite the temp file when I
> update the original file containing any of this information (e.g.,
> IntellectualRights, abstract, methods).
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ropensci/EML/issues/158#issuecomment-226809129>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AANleicuVkjRj2cAeku5QqVR8bdDP7Hnks5qMsRegaJpZM4I252c>
> .
>
-- 

http://carlboettiger.info

**Comment by cboettig** [comment]
Okay, added `overwrite = TRUE` as well.  Let me know if there are other issues here or feel free to close this.

**Comment by cboettig** [comment]
Think this is all done, otherwise feel free to reopen.
