### ISSUE TITLE
definition for textDomain attributes

### ISSUE THREAD

**Issue by masalmon** [ropensci/EML#166]
As far as I've understood it, when defining an attribute in the textDomain one has to give both an `attributeDefinition` and `definition`. I currently use the exact same definition in both of them. 

I guess in some cases users will have different definitions but if in many cases they don't, I wonder whether the `set_attributes` function should use `attributeDefinition` as a definition if the `definition` is empty in the data frame defining attributes, maybe with a message? 

Note that I might be completely misunderstanding the role of `definition` vs. `attributeDefinition` for textDomain variables.

**Comment by cboettig** [comment]
Yeah, I've been puzzled by that as well, @mbjones might have a better answer.

As you have seen, `attributeDefinition` is needed for any attribute, while `definition` only applies to `textDomain`, but I'm not sure how they differ. I have seen EML in the wild that just repeats the same thing -- kinda feels like `definition` is just there so that `textDomain` isn't empty.  The normative docs are usually specific about these issues, but here it just [says](https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/./eml-attribute.html#definition):

> The definition describes the code with which it is associated in enough detail for scientists to interpret the meaning of the coded values.
> Example(s): high density, above 10 per square meter


Your proposal sounds reasonable to me as a default.  @mbjones ?

**Comment by cgries** [comment]
That's certainly what I am doing - just repeating the `attributeDefinition` in the `definition`. So, I like the proposal too.

**Comment by cboettig** [comment]
Recommended using the same values for textDomain/definition as in attributeDefinition in the vignette.
