### ISSUE TITLE
set_coverage argument date

### ISSUE THREAD

**Issue by maelle** [ropensci/EML#172]
I had written a wrong issue because the documentation states that the argument has to be a character, sorry.

However I wonder whether/how the format of `begin`, `end`, and `date` should be checked.

**Comment by cboettig** [comment]
Well, it's still a good point that users might expect to be able to give a date object, so ultimately it is probably better if the coverage methods coerce to character internally rather than putting the burden on the user.

However, I went with asking for a character for the time being since I haven't had a chance to check that coercing any date to a character always does the right thing (i.e. if users give a date object, should they also manually give the format string for printing as character? or do we just always make it an ISO8601 date?).  Also, I think we need to have character as as at least an optional type for all date objects, since in R, any POSIX date object resolves to a full date (year-mo-day), while EML permits less precision in many dates (e.g. just the year.  Many EML files also tend to give date components split over columns; not sure how I feel about that).

**Comment by masalmon** [comment]
I think I saw that EML date had to be ISO something if it is a real date. Your point about year only is interesting. So if the user inputs a date it should be coerced internally to a character with the right format. If it is a character it should be left as such, which is a pity in a way because any character would be accepted, but there is no way to check the date makes sense.

Having the date split into several columns seems less important for now IMO.

**Comment by mbjones** [comment]
Yes, EML dates are ISO 8601 dates, and validated as the union of xsd:date and xsd:gYear types.  So there is a very restricted set of allowed formats.
