### ISSUE TITLE
Literature coercions

### ISSUE THREAD

**Issue by maelle** [ropensci/EML#174]
I see there is an article example of a literature file [here](https://github.com/ropensci/EML/blob/master/inst/xsd/test/eml-literature.xml)
- How to create example for the other types that are described in `literature_coercions.R`?
- For many fields/slots, should `from@blabla` be replaced with an `ifelse` statement for the case in which `blabla` is missing (for instance not all books are part of a series)? If it is missing what should be the value, `NA` or `""`?
- I see the fixme regarding dates. In a `bibentry` respecting Endnote format, do we expect `from@pubDate` to have a given format?

**Comment by masalmon** [comment]
Moreover I got this error when trying to create a book citation: `Error in as(from@publisher, "person") : 
  no method or default for coercing “publisher” to “person” `.

**Comment by cboettig** [comment]
Great questions, sorry I missed this thread earlier.  Will have to take a look and see how to fix that, I think the EML notion of `publisher` cannot necessarily be mapped to the R notion of `person`.  

It's somewhat unfortunate that EML literature fields are based around Endnote metadata model, rather than bibtex (like R and most other systems).  Something of a historical spandrel. For missing fields, NA is probably best.  I'd have to double-check though, `""` may still result in EML omitting the element.  

Right, we should have examples of the other coercions -- as you've seen they aren't in their yet since I haven't tested them all anyhow.  

Yup, pubDate is a bit tricky, particularly since bibtex splits dates into separate fields for year & month I believe (recurrent issue with dates here: whether to treat dates as Dates or strings, and what to do when they are split into multiple fields).

**Comment by cboettig** [comment]
Closing this in favor of the direct bibtex support now in EML 2.2.0, though we probably need examples of that.
