### ISSUE TITLE
add Appveyor CI?

### ISSUE THREAD

**Issue by masalmon** [ropensci/EML#175]

**Comment by cboettig** [comment]
@sckott @jeroenooms I think I'm having issues writing platform-independent paths, caussing my Appveyor checks to fail: https://ci.appveyor.com/project/cboettig/eml  Any advice on what I'm doing wrong? 

Here's the failing tests: https://github.com/ropensci/EML/blob/master/tests/testthat/test-TextType.R

Here's probably the responsible code: https://github.com/ropensci/EML/blob/master/R/set_TextType.R#L68-L90

Thanks!

**Comment by sckott** [comment]
seems liker https://ci.appveyor.com/project/cboettig/eml/build/1.0.3#L524 suggests that authentication didn't happen correctly

**Comment by cboettig** [comment]
@sckott I think that's a different issue; anyway, just fixed that line so it loads that test file from a local dir instead of downloading over https.  But those `TextType` tests still fail -- they use calls to pandoc via the `rmarkdown` package, and have to do some ugliness with working directories.  

I think the pandoc call is failing (gives this warning): 

```
Warning: running command ' +RTS -K512m -RTS hf205-abstract.docx --to docbook --output "C:/Users/appveyor/AppData/Local/Temp/1\RtmpEDBE06\file82061227188.xml" -s' had status 127
```

which causes the test to fail.  What puzzles me is that the path uses both `\` and `/` separators in the path `C:/Users/appveyor/AppData/Local/Temp/1\RtmpEDBE06\file82061227188.xml`.  The latter part, `\RtmpEDBE06\file82061227188.xml`, is coming from `file.path()` which I thought was supposed to be platform independent.  Doesn't windows use `\` as the directory separator?  Color me confused.

**Comment by jeroenooms** [comment]
Try wrapping the path in `normalizePath` to make it cross platform.

**Comment by cboettig** [comment]
Thanks, I'll try that.  I'm confused why `normalizePath` asks me to manually set `winslash` though, and defaults to a back slash, `\\`, while `file.path` uses `fsep = .Platform$file.sep` to determine the separator, has a Note that says: "The components are by default separated by / (not \) on Windows."  (i.e. contradicting the `winslash` default in `normalizePath`).  

On Appveyor, it seems `.Platform$file.sep` corresponds to back slash, `\\`, while paths generated on Appveyor using calls like `tempdir` use a forward slash `/`.  

In any event, neither choice for winslash seems to make my tests pass on Appveyor.  I'm mighty confused.

**Comment by cboettig** [comment]
So, no luck with `normalizePath`; though the problem might be to do rather with pandoc running on windows and perhaps has nothing to do with the paths. 

Anyway, closing this since Appveyor is now added, and skipping the pandoc-based tests on appveyor for now... Thanks for the suggestions all the same!

**Comment by sckott** [comment]
@cboettig  do you have a windows machine (virtual or otherwise) you can test in ?

**Comment by jeroenooms** [comment]
You can try the r-hub builders which gives detailed error messages on many platforms: https://builder.r-hub.io/advanced
