### ISSUE TITLE
Unhandled edge case in `eml_get`

### ISSUE THREAD

**Issue by amoeba** [ropensci/EML#190]
A student came across this today and I think it's a bug. When I run:

```
library(EML)
> doc <- new("eml")
> eml_get(doc, "creator")
Error in out[[1]] : subscript out of bounds
```

It looks like the line of offending code is https://github.com/ropensci/EML/blob/master/R/eml_get.R#L47 which results in an error when there is no element found, as in the case with an empty `eml` object. Doing a bit of debugging, the `out` variable ends up as an empty `list()` in this case:

```
> out
list()
```

I'm happy to write up a fix that returns from `eml_get` early when nothing was found. But what's the appropriate thing to do/return in this case?

**Comment by cboettig** [comment]
I believe that the correct return behavior for `eml_get(doc, "object")` should be a list containing the whose elements are the same as what is returned by `doc@path@to@object` for all possible paths to that object (whether or not `object` slot is empty).  I think the empty list is thus the right expected behavior if there are no matches (e.g. some elements, like `creator`, can appear in so many different possible paths, and we only want the ones that exist, not all the optional empty slots).   Does that make sense?  

As always a PR fix would be awesome.

**Comment by amoeba** [comment]
It does, empty list made sense to me too. Will PR.
