### ISSUE TITLE
Extracting character vectors from leaf nodes

### ISSUE THREAD

**Issue by amoeba** [ropensci/EML#194]
I just finished answering a question from someone on our team and found that my solution didn't seem all that great, though it worked. They wanted to get the abstract out of an EML document as a character vector. Their doc was something like this...

```{xml}
<eml>
  <dataset>
    <abstract>
      <para>
        My abstract is here...
...
```

And I told them they could run this:

```{r}
as(doc@dataset@abstract@para[[1]]@.Data[[1]], "character")
[1] My abstract is here...
```

I am wondering if there is an easier way. The first argument (the S4 path) isn't so much the problem here but it's that this solution requires them to understand more than I think is reasonable for the average intended user. To answer their question, I ended up reading the XML package source because I had forgotten that `as.character` isn't the same as `as(x, "character")`.

**Comment by cboettig** [comment]
Right, in general an abstract is a `textType`, so it can be an arbitrary combination of `para` or `section` elements with docbook-like markup, something that may not lend itself to rendering as a character string.

The intended workflow for this is that the user would use `get_textType` to render it to the desired type.  Here I use markdown as the best equivalent of a plain-text character string.

```r
## an example EML file
f <- system.file("examples/hf205.xml", package = "EML")
eml <- read_eml(f)

## Grab and parse abstract as markdown
abstract <- eml_get(eml, "abstract") 
get_TextType(abstract[[1]], "markdown", "abstract.markdown")

readLines("abstract.markdown")
```

Some users might prefer to render the text to `docx` or `html`, though of course that's really only necessary if there's actually fancy formatting involved.  In general an abstract element can just be a plain string as well of course, but since it's not guaranteed we need these methods.  

Does this work better for you?  (Note I just pushed a fix to this actually, since the docbook conversion step wasn't always working. Also this assumes `rmarkdown` is installed, even though it's a suggest and not a depends).

**Comment by amoeba** [comment]
Ah, I hadn't tried that function yet. And your explanation of why this is so complex makes sense. Looking at the definition of the text type in EML makes this make even more sense! The `get_TextType` function might work but I guess the hope was to save steps.

The workflow we're doing is halving the length of the abstract within thousands of EML documents in batch. Our first problem is to define what we mean by 'the abstract' and the second problem is getting it into a form where we can truncate it.

For the very simple case, like what I gave above, it would be possible to convert from the abstract (in the EML sense) into a single character vector holding the abstract content. But this is only because of how simple the example is. Is there any merit in producing a helper method that does the least surprising thing in simple cases?

**Comment by cboettig** [comment]
Good points. A few ideas:

`get_TextType` should probably be modified to have an option to return a character-vector object directly, rather than making the user write the file to markdown and read it back in.  Ideally the function should use some logic to first decide if the node is making use of the docType markup (that is, either `node@section` or `node@para` is not empty for any node for which `is(node, "TextType")` is true, such as `abstract`).  If both those slots are empty, then the node just has character data like in your example above already, and we should just read and return that.  Otherwise it's probably necessary to do the markdown trick (internally this time, returning a concatenated character string directly) to get text that looks like plain text, unless we just want to treat the docbook text like a literal string.  

A word of warning: using pandoc we're literally using docbook, while EML only implements a subset of docbook.  This shouldn't be any problem for this direction (From EML into other formats) but it could create issues if users try going the other way with too much fancy formatting).  

Anyway, did that make any sense?  Maybe I didn't follow what you had in mind.

**Comment by amoeba** [comment]
That all makes sense. Though I'm actually totally lost as to what I think is a good resolution to this Issue. I feel like the `get_TexType` function may get confusing if it handles both the R-like way (character vectors, list of char. vectors) and the docbook way but maybe it's not all that confusing. I guess my concern is that one approach (docbook) maintains the structure/semantics and the other way (the R way) throws that all out the window. And a function which does both things may be confusing.

By the way: Here's my current best code for truncating my example document:

```
doc <- read_eml(...)
abstract <- as(doc@dataset@abstract@para[[1]]@.Data[[1]], "character")
abstract <- substr(abstract, 1, nchar(abstract)/2)
doc@dataset@abstract@para[[1]]@.Data <- list(abstract)
```

I share it just to share what a package user is doing. I'd argue that this interface is somewhat hard to use but I don't have any fancy ideas for how to improve things.

If you think extending `getTextType` makes sense, I'd happily create an Issue for the task.

**Comment by cboettig** [comment]
Right, thanks for the example; clearly not ideal since it's both verbose and fragile (abstract need not be in `abstract@para[[1]].@Data`, it could be in `abstract@.Data` or `@abstract@section@...` etc.  

I think you want something like:

```r
doc <- read_eml(...)
abstract <- get_abstract(eml, as = "character")
```

That could work with a simple wrapper around `get_TextType`.  In any event I think the user should never have to think about `docbook`, because most will have no idea what it is, but the EML package function should always have to think about it since it needs to be able to handle the possibility of that kind of markup.  

I agree we need a utility to make character string return object a first-class citizen, since most programmatic use will want that (e.g. pull all abstracts into R and search for keyword matches).  That'll be true of any `TextType` element in EML as well, so I think it's a good idea to build that in.  I think we need to either rely on using markdown (well, could be any other text format built into pandoc) as the best equivalent representation for rich markup in plain text.

**Comment by amoeba** [comment]
To clarify, are you thinking that a call to `get_abstract` would always return a character vector of length one, regardless of the child elements contained in the `abstract` element and that the character vector would be essentially Markdown?

**Comment by cboettig** [comment]
Yes. How does that sound?

**Comment by amoeba** [comment]
I think I like it. I think that works for my specific use case too because truncating the abstract at an arbitrary length and converting that back into XML should work. Will it? I'm thinking of cases like this:

**Original**
```{markdown}
# section one

my section content

# section two

something
```

**Truncated**
```{markdown}
# section one

my section content

#     <- truncated section title, does this convert gracefully back into XML?
```

I'd be happy to take a crack at implementing this.

**Comment by cboettig** [comment]
There's really no truncation going on.  e.g. EML file might look like:

```xml
<abstract>
  <section>
   <title> Question/Methods </title>
   <para> text text text </para>
  <section>
  </section>
   <title> Results/Conclusions </title>
   <para> text text <bold>text</bold> </para>
  </section>
</abstract>
```

This would be rendered as markdown, which can then be read in as a length 1 character vector (with newline encoding):

```markdown
# Question/Methods

text text text

# Results/Conclusions 

text text text
```

Note that because we're using pandoc, we have no trouble rendering the markdown version back into the original docbook XML, and vice versa (or any other format).  

sound good?  

Sure, you're welcome to take a crack at an implementation, I think it would use a process similar to what I outlined above (after `readLines` you'd just want to do `paste(..., collapse="\n)` if we want the length-1 character vec. )

**Comment by amoeba** [comment]
Great, will do.

**Comment by cboettig** [comment]
closing as I think we've resolved this, but re-open a new issue if there are outstanding issues on set_textType behavior in current version.
