### ISSUE TITLE
indicate software used to create EML file

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#203]
@mbjones What would be the appropriate way to indicate that an EML file is generated from the EML R package (or is generated by Morpho, etc?)  Is that the `system` attribute by any chance? 

Also, what would be the best string to refer to the EML R package? The URL to the CRAN page for the package? Or better to use the DOI for the current release of the package? (If system is the attribute, I understand system expects a URI formatted string I think?)

**Comment by mbjones** [comment]
Good question, @cboettig. After thinking about it a few minutes, I don't think there is an appropriate field dedicated to this.  The closest things I can think of are 1) associatedParty with a role of `MetadataProvider`, and 2) the `/eml/dataset/maintenance` subtree, in particular its `description` element.  Neither of those are particularly good fits.  Seems you are looking for a user agent type of field.  With XML editors, I've seen that kind of metadata embedded in XML comments, but that's not very accessible.  I suppose the best thing to do would be to add it to `/eml/additionalMetadata` with a specific key like `<userAgent>` or somesuch.  Or it could be added as an optional field to EML.  Others have asked about a metadata update date for compatibility with ISO, and this would be similar.

**Comment by mbjones** [comment]
For citing the package, best to cite the DOI:

`doi:10.5063/F1M61H5X`

But note that DOIs are not technically URIs, even though they follow the syntax, because they are not registered at IANA as a URI scheme.

Oh, and the user-agent string for the R `dataone` package incorporates a bunch of version info.  But note it is not exported into the namespace, but is used internally to set the User-Agent: HTTP header fields when sending requests to DataONE nodes.

```r
> dataone:::get_user_agent()
[1] "dataone/2.0.1 R/3.3.2 httr/1.2.1"
> 
```

**Comment by cboettig** [comment]
@mbjones Thanks!  NeXML provides the top-level attribute `generator` to encode this (e.g. https://github.com/ropensci/RNeXML/blob/master/inst/examples/biophylo.xml).  What would it look like as an additional optional field?  Otherwise the `additionalMetadata/userAgent` sounds good to me, (since it's more top-level than having it somewhere in `/eml/dataset`.  

In other news, I'm still a bit unclear about the `system` attribute, and what we should be using as a default.  I see a lot of example files have `system="knb"`, and I believe it has something to do with the source/provider of the identifier in `packageId`.  But I'd like the ability for `write_eml` to output a local, valid EML file without uploading it.  I guess we could generate UUIDs on the fly and then system would be UUID?  

Alternatively, I've thought about not introducing a hard dependency on UUID, and use R's internal unique string (e.g. from `tempfile()` routine, but I suppose that may be too weak for an ID).  Presumably this ID gets updated to something more official if/when a user uploads the metadata to DataONE (though changing IDs seems a bit odd?).  I see your note that KNB only recognizes UUID and DOIs, so perhaps we should really have the hard dependency on UUID and default to `system="uuid"` ?

**Comment by mbjones** [comment]
The `system` attribute is intended to be a scoping namespace for the associated identifier field on that element (either `id` or `packageId`) -- declaring a system is meant to be a declaration that the identifier string is unique within the namespace defined in `system`.  The problem is that, in terms of implementation, there is no standard way to express namespaces in a controlled way, so people just put whatever qualifier they want in the field. Historically, we used `knb` as an indicator that the dataset was uploaded to the KNB and therefore the identifier is unique in that repository.   In retrospect, that was not very useful or effective, and we would have been better served if all `system` values were URIs that defined namespaces for their associated identifiers.  If only there were a well established vocabulary for namespaces, so that it was clear what URI to use for UUID versus DOI versus repository-specific identifiers like RRIDs and even bare strings as used in some repos (e.g., 'foo.1.1').

My recommendation today is:  1) use globally unique identifiers always 2) use a URI for the system attribute that is appropriate for that type of identifier system (e.g., http://doi.org for DOIs).

In our systems, the identifier is NOT updated when it is uploaded -- rather, the user is responsible for proposing an identifier that is unique and populating the content appropriately.  This is mainly because, in the world of heterogeneous metadata and data standards, its not always evident where those identifiers would need to be changed in each standard. SO we leave it in the responsibility of the submitter, but we verify uniqueness upon insert.

**Comment by amoeba** [comment]
Since identifiers such as UUIDs and DOIs are essentially (or are at least intended to be) globally unique, would providing a `system` attribute of 'global' be appropriate?

**Comment by cboettig** [comment]
@mbjones Thanks, super helpful.  So if we default to a UUID for the `packageId`, then `system` should be `urn:uuid`?  Is that a valid and correct URI for this case?

**Comment by mbjones** [comment]
@cboettig Unfortunately, "urn:uuid" is not a valid URI, because the UUID URN namespace as defined in [RFC 4122](https://www.ietf.org/rfc/rfc4122.txt) requires that "urn:uuid" be followed by the value of the UUID, such as "urn:uuid:cd0ec80f-d838-430d-9fcd-db4943c28684". I'm not sure there is a valid namespace URI for the concept of UUID URI space. Maybe the URI of the RFC 4122 specification (https://www.ietf.org/rfc/rfc4122.txt)?  Open to ideas here.  As `system` is not typed as a URI, you could also use 'urn:uuid' or just plain "UUID", or even "global" as @amoeba suggested, but I think a sensible URI would be better.  Bottom line: our community has not reached agreement on how to use `system` consistently.
