### ISSUE TITLE
Quote parsing issue

### ISSUE THREAD

**Issue by jsta** [ropensci/EML#301]
If I run the README examples up to and including the [Putting it all together chunk](https://github.com/ropensci/EML#putting-it-all-together), I get an error upon running `eml_validate`:

```r
> eml_validate(my_eml)
[1] FALSE
attr(,"errors")
[1] "Element 'quote': This element is not expected." "Element 'quote': This element is not expected."
[3] "Element 'quote': This element is not expected." "Element 'quote': This element is not expected."
```

The error no longer occurs if I strip the quotes out of [inst/examples/hf205-methods.md](https://github.com/ropensci/EML/blob/master/inst/examples/hf205-methods.md)

I am running the latest CRAN release (2.0.2)

**Comment by amoeba** [comment]
Hey @jsta thanks for the report. What's going on here isn't readily apparent to me. I can't reproduce this on my Mac or Windows 10 machines when I run the README. They're both on R 4.0 and EML 2.0.2. Because this also involves Pandoc, we might look at your version. I can't reproduce this with 2.7.2 (Windows) and 2.9.2.1 (Mac).

Could you share a `devtools::session_info()`, your Pandoc version, your operating system, and an XML-serialized copy of that `my_eml` object?

**Comment by jsta** [comment]
Well, I took the plunge upgrading to R 4.0 and I no longer see this error. :shrug:

**Comment by amoeba** [comment]
FWIW I also couldn't reproduce on R 3.6.3. Do let us know if you see it again and thanks for reporting.
