### ISSUE TITLE
set_attributes forces all numeric fields to have storageType = "float"

### ISSUE THREAD

**Issue by mmfink** [ropensci/EML#324]
Regardless of whether a numeric field is an integer, the set_attributes() command writes the storageType as "float". The source of this is line 454 in set_attributes.R -

```
    ## storage type is optional, maybe better not to set this?
    storageType[col_classes == "numeric"] <- "float"
    storageType[col_classes == "character"] <- "string"
    storageType[col_classes %in% c("factor", "ordered")] <- "string"
    storageType[col_classes %in% c("Date")] <- "date"
```

I may be missing the finer points of the storageType attribute, but this seems like it misrepresents the properties of an integer field?

**Comment by cboettig** [comment]
Actually EML doesn't have types for "integer" or "float", see [measurementScales](https://eml.ecoinformatics.org/schema/eml-attribute_xsd.html#AttributeType_measurementScale).  Numeric measurements in EML can be "interval" or "ratio", though set_attributes() only maps numeric data to "ratio".

Of course "integer" data could be used to encode factors, (nominal or ordinal types in EML), or even dates! (the atomic type of a date in R is integer).  So as you see, the map between what EML uses for measurementScale and data encodings in R is not at all straight-forward -- really we have no business guessing just about any measurementScale from the R class to begin with.  

But  `set_attributes()`, like all set_ methods, is really just a convenience function that covers common cases, where it's reasonable for a user to assume that EML will have _some_ notion to distinguish numeric values from dates, etc, so it does a best-attempt to map the R class to an EML class.  measurementScale is a required element, so set_attributes() does it's best to help users out by mapping R atomic types to measurementScales.  

As you observe, storageType is an optional EML attribute that accompanies measurement scale, but is actually a little closer to the notion of datatype (i.e. it's supposed to be an XML Schema storage type, xs:string, etc), so while we were at it we went and mapped those too.  Agree that it would obviously be better to map an integer to xs:integer, but set_attributes() is taking a short-cut here that is trying to do the mapping based on the same choice it made for the measurementScale, which is obviously not great.  But set_attributes isn't inspecting the actual values of a data.frame, it is just getting the class passed in an argument.

Note by default, a `numeric` is a double-precision floating point in R, witness:

```r
 is.double(numeric(1L))
```

though perhaps confusingly,  `is.numeric(integer(1L))` is also true.  Overall we are possibly better just omitting this, as the comment suggests.  I'm not sure how to improve the guessing based on the simplified interface that set_attributes() presents to the user though.  

In practical terms, storageType seems to have relational databases in mind, though it's certainly useful sometimes to know if `read_csv()` should default to integer or a float (though describing a csv file containing a number as having "(double) floating point precision" is perhaps misleading?)  At the end of the day, where datatypes are important it's probably necessary to use a data format that encodes the type rather than rely on the metadata?


A user can always have more fine-grained control by constructing the EML more explicitly, e.g. with lists (or with https://github.com/cboettig/build.eml ).

**Comment by mmfink** [comment]
@cboettig Thank you for the well considered reply, those are all good points. I had started out supplying storageType and col_classes to set_attributes() so that the code would fill in the measurementScale, but the validation code for storageType will not accept "integer".

So instead I have switched to supplying numberType (as "real" or "integer") and col_classes - as shown in the package vignette. That works, but I found it inconsistent that set_attributes() still filled in all numeric storageTypes as "float", regardless of numberType. Your points about how R regards numeric values perhaps makes this all moot (as well as your point about not being required to use set_attributes()). On the other hand, this could just be a matter of allowing the storageType validation code to accept "integer". 😃

**Comment by mbjones** [comment]
No worries, @mmfink, the difference is in how they are defined in the schema. The storageType behavior is determined by the code in the EML package, whereas the EML schema says it can be any string value. In contrast, the `NumberType` definition in the EML schema restricts the field to only have one of the 4 enumerated values through an xs:restriction. You can see the definition here: https://eml.ecoinformatics.org/schema/eml-attribute_xsd.html#NumberType  The R package might let you put anything in that field, but any value other than `natural`, `whole`, `integer`, and `real` should produce a schema validation error when you try to validate with the R package.

**Comment by mmfink** [comment]
Thanks for accepting the PR. Closing.
